clear; clc;
syms x y z x0 y0 z0 r0 gamma d1xdt d1ydt d1zdt; 
gamma=1;
h = (x-x0)^2 + (y-y0)^2 + (z-z0)^2 - r0^2;
h2 = jacobian(h,[x y z])*[d1xdt; d1ydt; d1zdt] + gamma*h;
B = h2;
dBdx = jacobian(B,[x y z d1xdt d1ydt d1zdt]);
m_list_x = {'x', 'x(1)' ; 'y', 'x(2)' ; 'z', 'x(3)' ; ...
            'd1xdt', 'x(4)' ; 'd1ydt', 'x(5)' ; 'd1zdt', 'x(6)' ; ...
            };
m_list_params = {'x0', 'params(1)' ; ...
                 'y0', 'params(2)' ; ...
                 'z0', 'params(3)' ; ...
                 'r0', 'params(4)'} ;
write_fcn_m(['fcn_expCBF_PointMass.m'],{'x', 'params'},[m_list_x;m_list_params],{B,'B'; dBdx,'dBdx'});