clear; clc;
syms x y z x0 y0 z0 r0 gamma d1xdt d1ydt d1zdt d2xdt d2ydt d2zdt d3xdt d3ydt d3zdt; 
gamma=2;
h = (x-x0)^2 + (y-y0)^2 + (z-z0)^2 - r0^2;
h2 = jacobian(h,[x y z])*[d1xdt; d1ydt; d1zdt] + gamma*h;
h3 = jacobian(h2,[d1xdt d1ydt d1zdt])*[d2xdt; d2ydt; d2zdt] + gamma*h2;
h4 = jacobian(h3,[d2xdt d2ydt d2zdt])*[d3xdt; d3ydt; d3zdt] + gamma*h3;
B = h4;
dBdx = jacobian(B,[x y z d1xdt d1ydt d1zdt d2xdt d2ydt d2zdt d3xdt d3ydt d3zdt]);
m_list_x = {'x', 'x(1)' ; 'y', 'x(2)' ; 'z', 'x(3)' ; ...
            'd1xdt', 'x(4)' ; 'd1ydt', 'x(5)' ; 'd1zdt', 'x(6)' ; ...
            'd2xdt', 'x(7)' ; 'd2ydt', 'x(8)' ; 'd2zdt', 'x(9)' ; ...
            'd3xdt', 'x(10)' ; 'd3ydt', 'x(11)' ; 'd3zdt', 'x(12)' ; ...
            };
m_list_params = {'x0', 'params(1)' ; ...
                 'y0', 'params(2)' ; ...
                 'z0', 'params(3)' ; ...
                 'r0', 'params(4)'} ;
write_fcn_m(['fcn_expCBF_IntChainDeg4.m'],{'x', 'params'},[m_list_x;m_list_params],{B,'B'; dBdx,'dBdx'});